### PR TITLE
#20 Cleaning exception messages with weird chars

### PR DESCRIPTION
**Pull request by antidata**

### CODE REVIEW

**Comment by antidata** [comment]
Greeting @joescii, any chance to get a new build soon including this change? Thanks!!

**Comment by joescii** [comment]
Sorry for my slow response to your PR. Had a busy couple of weeks. Once I merge #19, I'll be able to test and merge. Thanks.

**Comment by joescii** [comment]
Well last night I published 0.9.4, but thanks to a midnight-piloting error I somehow didn't successfully pull your changes locally after I branched. I'm guessing it failed and I didn't notice, lol. I'll try to get this out later today as 0.9.5.

**Comment by joescii** [comment]
After running some tests, I think we're cleaning up _too_ much. You can see the white space is removed in this test failure:

```
[info] - should convert a failed Future[String] to a satisfied LAFuture(Failure[String]) *** FAILED ***
[info]   Full(Failure(thefuturefailed,Full(java.lang.Exception: the future failed),Empty)) was not equal to Failure(the future failed,Full(java.lang.Exception: the future failed),Empty) (FutureConversionsSpecs_2.10.scala:28)
```

Instead of `"the future failed"` we're getting `"thefuturefailed"'. 

Based on our email discussion, the concern is newline characters breaking the JSON response. I'm sure there are plenty of other characters which could do this. Take a look at [this commit](https://github.com/joescii/lift-ng/commit/1169850eebef59d56ac6225932b595c17aa88261). I'm going to post it on the Lift forum to see if it's our best option.

**Comment by joescii** [comment]
Got it worked out and released as 0.9.5!

**Comment by antidata** [comment]
Thanks!

**Pull request merged**
